name: at_notify_flutter
description: A Flutter plugin project to send notification to any atSign in
  atPlatform apps with ease.
version: 1.0.8
homepage: https://atsign.dev
repository: https://github.com/atsign-foundation/at_widgets/tree/trunk/packages/at_notify_flutter
issue_tracker: https://github.com/atsign-foundation/at_widgets/issues
documentation: https://docs.atsign.com/

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  at_client: ^3.0.72
  at_client_mobile: ^3.2.12
  at_common_flutter: ^2.0.12
  at_commons: ^4.0.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.3.2

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  plugin:
    platforms:
      android:
        package: com.atsign.at_notify_flutter
        pluginClass: AtNotifyFlutterPlugin
      ios:
        pluginClass: AtNotifyFlutterPlugin
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
