# include: package:lints/recommended.yaml;

analyzer:
  errors:
    unused_local_variable: warning
    invalid_assignment: warning
    missing_return: error
    annotate_overrides: error
    always_specify_types: warning
    dead_code: warning
    todo: ignore

linter:
  rules:
    hash_and_equals: true
    prefer_is_not_empty: true
    always_specify_types: true
    avoid_print: false
    constant_identifier_names: false
    non_constant_identifier_names: false
    avoid_type_to_string: true
    camel_case_types: false
    not_initialized_non_nullable_instance_field: true
    empty_constructor_bodies: true
    prefer_const_constructors: true
    sort_constructors_first: false
    prefer_single_quotes: true
    avoid_empty_else: true
    cancel_subscriptions: true
    close_sinks: true
    prefer_conditional_assignment: true
    cast_nullable_to_non_nullable: true
    omit_local_variable_types: false
    avoid_returning_null_for_future: true
    always_declare_return_types: true
    avoid_returning_null: true
    avoid_returning_null_for_void: true
    avoid_returning_this: true
    implementation_imports: false
    avoid_void_async: true
    unawaited_futures: true
    await_only_futures: true
    unnecessary_lambdas: true
    unnecessary_await_in_return: true
    unnecessary_final: true
    sort_pub_dependencies: false
    package_names: true
