name: at_chat_flutter
description: A Flutter plugin project to provide a chat feature between atSigns built on the atPlatform to any Flutter application.
version: 3.0.7
homepage: https://docs.atsign.com/
repository: https://github.com/atsign-foundation/at_widgets/tree/trunk/at_chat_flutter
issue_tracker: https://github.com/atsign-foundation/at_widgets/issues
documentation: https://atsign.dev/docs/functional_architecture/libraries/#at_chat_flutter

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  at_contact: ^3.0.7
  at_common_flutter: ^2.0.11
  at_commons: ^3.0.26
  at_client_mobile: ^3.2.7
  at_client: ^3.0.40
  at_lookup: ^3.0.32

  #Picker
  file_picker: ^4.3.3

dev_dependencies:
  flutter_lints: ^1.0.4
  mocktail: ^0.3.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.atsign.at_chat_flutter
        pluginClass: AtChatFlutterPlugin
      ios:
        pluginClass: AtChatFlutterPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
