name: at_login_flutter
description: A flutter library for zero trust logins using the atProtocol
version: 0.0.2
homepage: https://docs.atsign.com/

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  at_client: ^3.0.72
  at_client_mobile: ^3.2.12
  at_commons: ^4.0.1
  at_server_status: ^1.0.3
  at_utils: ^3.0.15
  basic_utils: ^5.6.1
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^15.1.1
  flutter_qr_reader: ^1.0.5
  http: ^1.1.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  provider: ^6.0.5
  crypton: ^2.1.0

dependency_overrides:
  at_client_mobile:
    git:
      url: https://github.com/atsign-foundation/at_client_sdk.git
      path: packages/at_client_mobile
      ref: trunk

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.example.at_login_flutter
        pluginClass: AtLoginFlutterPlugin
      ios:
        pluginClass: AtLoginFlutterPlugin
      macos:
        pluginClass: AtLoginFlutterPlugin
  #      web:
  #        pluginClass: AtLoginFlutterWeb
  #        fileName: at_login_flutter_web.dart
  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
