# include: package:flutter_lints/flutter.yaml
include: package:lints/core.yaml

# analyzer:
#   errors:
#     unused_local_variable: warning
#     invalid_assignment: warning
#     missing_return: error
#     annotate_overrides: error
#     always_specify_types: warning
#     dead_code: warning
#     todo: ignore
#   exclude: [build/**]

# linter:
#   rules:
#     camel_case_types: true
#     unnecessary_statements: true
#     library_private_types_in_public_api: false
#     no_leading_underscores_for_local_identifiers: false