name: at_onboarding_flutter
description: A Flutter plugin project for onboarding any atSign in atPlatform
  apps with ease. Provides a QRscanner option and an upload key file option to
  authenticate.
version: 6.1.5
homepage: https://docs.atsign.com/
repository: https://github.com/atsign-foundation/at_widgets/tree/trunk/packages/at_onboarding_flutter
issue_tracker: https://github.com/atsign-foundation/at_widgets/issues
documentation: https://docs.atsign.com/

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  archive: ^3.3.9
  at_backupkey_flutter: ^4.0.10
  at_client: ^3.0.64
  at_client_mobile: ^3.2.12
  at_commons: ^4.0.0
  at_server_status: ^1.0.3
  at_sync_ui_flutter: ^1.0.8
  at_utils: ^3.0.15
  file_picker: ^5.5.0

  # desktop - dependencies
  file_selector: ^1.0.1
  file_selector_linux: ^0.9.2+1
  file_selector_macos: ^0.9.3+2
  file_selector_windows: ^0.9.3+1
  flutter:
    sdk: flutter
  http: ^1.1.0
  image: ^4.0.17
  intl: ^0.17.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  pin_code_fields: ^8.0.1
  qr_code_scanner: ^1.0.1
  shared_preferences: ^2.2.1
  tutorial_coach_mark: ^1.2.11
  url_launcher: ^6.1.14
  webview_flutter: ^4.2.4
  zxing2: ^0.2.0

dependency_overrides:
  at_auth:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: packages/at_auth
      ref: refactor_enrollment_methods
  file_selector: ^1.0.0
  at_client:
    git:
      url: https://github.com/atsign-foundation/at_client_sdk.git
      path: packages/at_client
      ref: apkam_onboarding_changes_with_enrollment_status
  at_client_mobile:
    git:
      url: https://github.com/atsign-foundation/at_client_sdk.git
      path: packages/at_client_mobile
      ref: apkam_onboarding_changes_with_enrollment_status

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  mocktail: ^0.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.atsign.at_onboarding_flutter
        pluginClass: AtOnboardingFlutterPlugin
      ios:
        pluginClass: AtOnboardingFlutterPlugin
      macos:
        default_package: at_onboarding_flutter
      windows:
        default_package: at_onboarding_flutter
      linux:
        default_package: at_onboarding_flutter

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
  class_name: AtOnboardingLocalizations
  arb_dir: lib/localizations/l10n
  output_dir: lib/localizations/generated
