name: at_backupkey_flutter
description: A Flutter plugin project for saving the backup key of any atSign that is being onboarded with atPlatform apps. The backup key can be used to authenticate in other atPlatform apps.
version: 4.0.10
homepage: https://docs.atsign.com/
repository: https://github.com/atsign-foundation/at_widgets/tree/trunk/packages/at_backupkey_flutter
issue_tracker: https://github.com/atsign-foundation/at_widgets/issues
documentation: https://docs.atsign.com/

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  share_plus: ^7.0.2
  permission_handler: ^10.4.1
  path_provider: ^2.0.9
  at_file_saver: ^0.1.2
  at_utils: ^3.0.12
  at_client_mobile: ^3.2.11
  showcaseview: ^2.0.3
  device_info_plus: ^9.0.2
  # desktop - dependencies
  file_selector: ^0.9.5
  file_selector_macos: ^0.9.3
  file_selector_windows: ^0.9.3
  file_selector_linux: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.atsign.at_backupkey_flutter
        pluginClass: AtBackupkeyFlutterPlugin
      ios:
        pluginClass: AtBackupkeyFlutterPlugin
      macos:
        default_package: at_backupkey_flutter
      windows:
        default_package: at_backupkey_flutter
      linux:
        default_package: at_backupkey_flutter

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
