name: at_events_flutter
description: A Flutter plugin project to manage events (time, place and
  attendees) using the atPlatform.
version: 3.1.13
homepage: https://docs.atsign.com/
repository: https://github.com/atsign-foundation/at_widgets/tree/trunk/packages/at_events_flutter
issue_tracker: https://github.com/atsign-foundation/at_widgets/issues
documentation: https://docs.atsign.com/

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  at_client: ^3.0.72
  at_client_mobile: ^3.2.17
  at_common_flutter: ^2.0.13
  at_commons: ^4.0.1
  at_contact: ^3.0.8
  at_contacts_flutter: ^4.0.14
  at_contacts_group_flutter: ^4.0.15
  at_location_flutter: ^3.1.12
  at_lookup: ^3.0.40
  at_utils: ^3.0.15
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.2
  geolocator: ^12.0.0
  latlong2: ^0.9.0
  sliding_up_panel: ^2.0.0+1

dependency_overrides: 
  at_location_flutter:
    path: ../at_location_flutter

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.atsign.at_events_flutter
        pluginClass: AtEventsFlutterPlugin
      ios:
        pluginClass: AtEventsFlutterPlugin
  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
