name: at_follows_flutter
description: A Flutter plugin project that provides a basic social “follows” functionality for any @sign. Provides a list of @signs that follow you (followers) as well as the @signs that you follow (following) with the option to unfollow them.
version: 2.0.4
homepage: https://atsign.dev
repository: https://github.com/atsign-foundation/at_widgets

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  at_client_mobile: ^2.0.3
  at_commons: ^2.0.4
  at_lookup: ^2.0.4
  at_server_status: ^1.0.2
  at_utils: ^2.0.4
  collection: ^1.15.0
  flutter:
    sdk: flutter
  flutter_qr_reader: ^1.0.5
  permission_handler: ^8.1.1
  provider: ^5.0.0
  url_launcher: ^6.0.6
  webview_flutter: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.atsign.at_follows_flutter
        pluginClass: AtFollowsFlutterPlugin
      ios:
        pluginClass: AtFollowsFlutterPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/images/
    - assets/jsons/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
