include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [build/**]

linter:
  rules:
    camel_case_types: true
    unnecessary_statements: true
    library_private_types_in_public_api: false